name: demo
description: A "kitchen sink" demo of the Chicago widget set for Flutter
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.18.0"

dependencies:
  flutter:
    sdk: flutter
  chicago: any
  intl: any
  meta: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

dependency_overrides:
  chicago:
    path: ../
